['texture_image_generated_height', 'texture_image_use_generated_float', 'texture_point_density_falloff_speed_scale', 'bump_method', 'use_map_displacement', 
'texture_use_flip_axis', 'texture_use_mipmap_gauss', 'texture_weight_1', 'texture_weight_2', 'texture_weight_3', 'texture_noise_intensity', 'texture_gain', 
'texture_image_user_frame_start', 'type', 'bump_objectspace', 'texture_repeat_y', 'texture_repeat_x', 'warp_factor', 'texture_voxel_data_smoke_data_type',
 'texture_use_color_ramp', 'texture_point_density_speed_scale', 'emit_factor', 'texture_noise_distortion', 'normal_factor', 'texture_dimension_max', 'invert', 
 'texture_filter_size', 'texture_image_user_use_cyclic', 'texture_point_density_turbulence_strength', 'texture_use_filter_size_min', 'color', 'texture_contrast', 'use_map_normal', 
 'hardness_factor', 'texture_extension', 'texture_point_density_use_falloff_curve', 'texture_minkovsky_exponent', 'texture_environment_map_clip_start', 'texture_weight_4',
 'texture_noise_scale', 'use_map_translucency', 'blend_type', 'texture_crop_max_y', 'texture_crop_max_x', 'texture_distance_metric', 'texture_image_user_frame_offset', 
 'specular_color_factor', 'texture_image_use_fields', 'mirror_factor', 'texture_offset', 'texture_point_density_color_source', 'texture_musgrave_type', 
 'use_map_alpha', 'use_map_warp', 'texture_turbulence', 'texture_image_generated_width', 'texture_environment_map_resolution', 'texture_image_user_use_auto_refresh', 
 'texture_use_checker_even', 'texture_point_density_particle_cache_space', 'texture_crop_min_x', 'specular_factor', 'texture_point_density_use_turbulence', 
 'alpha_factor', 'use_stencil', 'normal_map_space', 'use_map_mirror', 'use_map_hardness', 'texture_factor_red', 'texture_use_checker_odd', 
 'texture_image_field_order', 'texture_environment_map_mapping', 'texture_voxel_data_filepath', 'texture_filter_type', 'texture_use_derivative_map', 'texture_factor_green', 
 'diffuse_color_factor', 'diffuse_factor', 'texture_wood_type', 'texture_use_interpolation', 'texture_noise_basis_2', 'texture_environment_map_depth', 'texture_color_mode',
 'texture_cloud_type', 'use_map_diffuse', 'texture_saturation', 'texture_image_user_fields_per_frame', 'texture_use_calculate_alpha', 'use_map_color_spec', 'texture_noise_depth', 
 'texture_environment_map_clip_end', 'use_map_color_diffuse', 'texture_use_mipmap', 'texture_voxel_data_use_still_frame', 'texture_noise_scale_2', 'default_value', 
 'texture_point_density_falloff', 'texture_environment_map_zoom', 'scale', 'texture_intensity', 'texture_image_use_premultiply', 'texture_point_density_turbulence_depth', 
 'use_from_dupli', 'mapping_z', 'texture_invert_alpha', 'mapping_x', 'mapping_y', 'texture_voxel_data_still_frame', 'translucency_factor', 'texture_point_density_turbulence_scale', 
 'texture_point_density_radius', 'texture_marble_type', 'texture_coords', 'use_map_specular', 'texture_factor_blue', 'texture_filter_eccentricity', 'texture_voxel_data_intensity', 
 'texture_point_density_vertex_cache_space', 'texture_use_normal_map', 'texture_environment_map_layers_ignore', 'use_map_ambient', 'mapping', 'texture_stucci_type', 
 'texture_voxel_data_extension', 'texture_voxel_data_interpolation', 'use_from_original', 'texture_image_generated_type', 'texture_environment_map_source', 'offset', 'use_map_emit',
 'texture_use_mirror_x', 'use_map_raymir', 'texture_nabla', 'texture_voxel_data_file_format', 'texture_noise_type', 'texture_use_mirror_y', 'texture_lacunarity', 'texture_crop_min_y',
 'texture_point_density_point_source', 'texture_progression', 'texture_filter_probes', 'texture_octaves', 'texture_image_user_frame_duration', 'texture_noise_basis',
 'texture_checker_distance', 'texture_point_density_turbulence_influence', 'ambient_factor', 'displacement_factor', 'texture_voxel_data_resolution', 'texture_distortion', 'raymir_factor', 
 'use_rgb_to_intensity', 'texture_use_alpha', 'num_textures', 'idx_materials', 'idx_color_ramp', 'idx_point_density_ramp', 'name', 'type', 'use_textures', 'texture_use_alpha']
 
    "texture_image_user_frame_start" INTEGER DEFAULT (0),
    "texture_image_user_frame_offset" INTEGER DEFAULT (0),
    "texture_image_user_fields_per_frame" INTEGER DEFAULT (0),
    "texture_image_user_use_auto_refresh" BOOLEAN DEFAULT (0),
    "texture_image_user_use_cyclic" BOOLEAN DEFAULT (0),
    "texture_voxel_data_interpolation" TEXT DEFAULT ('TRILINEAR'),
    "texture_voxel_data_extension" TEXT DEFAULT ('CLIP'),
    "texture_voxel_data_intensity" FLOAT DEFAULT (0_0),
    "texture_voxel_data_filepath" TEXT DEFAULT (''),
    "texture_voxel_data_resolution" TEXT DEFAULT ('(0, 0, 0)'),
    "texture_voxel_data_use_still_frame" BOOLEAN DEFAULT (0),
    "texture_voxel_data_still_frame" INTEGER DEFAULT (0),
    "texture_voxel_data_domain_object" TEXT DEFAULT (''),
    "texture_voxel_data_domain_object_name" TEXT DEFAULT (''),
    "texture_voxel_data_smoke_data_type" TEXT DEFAULT ('SMOKEDENSITY'),
    "texture_point_density_point_source" TEXT DEFAULT ('PARTICLE_SYSTEM'),
    "texture_point_density_object" TEXT DEFAULT (''),
    "texture_point_density_object_name" TEXT DEFAULT (''),
    "texture_point_density_radius" FLOAT DEFAULT (0_0),
    "texture_point_density_particle_system" TEXT DEFAULT (''),
    "texture_point_density_falloff" TEXT DEFAULT ('PARTICLE_VELOCITY'),
    "texture_point_density_falloff_speed_scale" FLOAT DEFAULT (0_0),
    "texture_point_density_particle_cache_space" TEXT DEFAULT ('WORLD_SPACE'),
    "texture_point_density_use_falloff_curve" BOOLEAN DEFAULT (0),
    "texture_point_density_color_source" TEXT DEFAULT ('CONSTANT'),
    "texture_point_density_speed_scale" FLOAT DEFAULT (0_0),
    "texture_point_density_use_turbulence" BOOLEAN DEFAULT (0),
    "texture_point_density_turbulence_influence" TEXT DEFAULT ('STATIC'),
    "texture_point_density_turbulence_scale" FLOAT DEFAULT (0_0),
    "texture_point_density_turbulence_depth" INTEGER DEFAULT (0),
    "texture_point_density_turbulence_strength" FLOAT DEFAULT (0_0),
    "texture_image_use_fields" BOOLEAN DEFAULT (0),
    "texture_image_use_premultiply" BOOLEAN DEFAULT (0),
    "texture_image_field_order" TEXT DEFAULT ('EVEN'),
    "texture_image_generated_width" INTEGER DEFAULT (0),
    "texture_image_generated_height" INTEGER DEFAULT (0),
    "texture_image_generated_type" TEXT DEFAULT ('BLANK'),
    "texture_image_use_generated_float" BOOLEAN DEFAULT (0),
    "texture_image_blob" BLOB DEFAULT ('None'),
    "texture_use_alpha" BOOLEAN DEFAULT (0),
    "texture_use_calculate_alpha" BOOLEAN DEFAULT (0),
    "texture_invert_alpha" BOOLEAN DEFAULT (0),
    "texture_use_flip_axis" TEXT DEFAULT ('HORIZONTAL'),
    "texture_use_normal_map" BOOLEAN DEFAULT (0),
    "normal_map_space" BOOLEAN DEFAULT (0),
    "texture_use_derivative_map" BOOLEAN DEFAULT (0),
    "texture_use_mipmap" BOOLEAN DEFAULT (0),
    "texture_use_mipmap_gauss" BOOLEAN DEFAULT (0),
    "texture_use_interpolation" BOOLEAN DEFAULT (0),
    "texture_filter_type" TEXT DEFAULT ('BOX'),
    "texture_filter_eccentricity" INTEGER DEFAULT (0),
    "texture_filter_size" FLOAT DEFAULT (1_0),
    "texture_use_filter_size_min" BOOLEAN DEFAULT (0),
    "texture_filter_probes" INTEGER DEFAULT (0),
    "texture_extension" TEXT DEFAULT ('CLIP'),
    "texture_repeat_x" INTEGER DEFAULT (0),
    "texture_repeat_y" INTEGER DEFAULT (0),
    "texture_use_mirror_x" BOOLEAN DEFAULT (0),
    "texture_use_mirror_y" BOOLEAN DEFAULT (0),
    "texture_crop_min_x" FLOAT DEFAULT (0_0),
    "texture_crop_min_y" FLOAT DEFAULT (0_0),
    "texture_crop_max_x" FLOAT DEFAULT (1_0),
    "texture_crop_max_y" FLOAT DEFAULT (1_0),
    "texture_use_checker_even" BOOLEAN DEFAULT (0),
    "texture_use_checker_odd" BOOLEAN DEFAULT (0),
    "texture_checker_distance" FLOAT DEFAULT (0_0),
    "texture_noise_distortion" TEXT DEFAULT ('BLENDER_ORIGINAL'),
    "texture_distortion" FLOAT DEFAULT (0_0),
    "texture_environment_map_source" TEXT DEFAULT ('ANIMATED'),
    "texture_environment_map_mapping" TEXT DEFAULT ('CUBE'),
    "texture_environment_map_viewpoint_object" TEXT DEFAULT (''),
    "texture_environment_map_viewpoint_object_name" TEXT DEFAULT (''),
    "texture_environment_map_layers_ignore" TEXT DEFAULT (''),
    "texture_environment_map_resolution" INTEGER DEFAULT (0),
    "texture_environment_map_depth" INTEGER DEFAULT (0),
    "texture_environment_map_clip_start" FLOAT DEFAULT (0_0),
    "texture_environment_map_clip_end" FLOAT DEFAULT (0_0),
    "texture_coords" TEXT DEFAULT ('ORCO'),
    "object" TEXT DEFAULT (''),
    "object_name" TEXT DEFAULT ('$T_Noname'),
    "uv_layer" TEXT DEFAULT (''),
    "uv_layer_name" TEXT DEFAULT (''),
    "use_from_dupli" BOOLEAN DEFAULT (0_0),
    "use_from_original" BOOLEAN DEFAULT (0_0),
    "mapping" TEXT DEFAULT ('FLAT'),
    "mapping_x" TEXT DEFAULT ('X'),
    "mapping_y" TEXT DEFAULT ('Y'),
    "mapping_z" TEXT DEFAULT ('Z'),
    "offset" TEXT DEFAULT ('(0_0, 0_0, 0_0)'),
    "scale" TEXT DEFAULT ('(0_0, 0_0, 0_0)'),
    "texture_use_color_ramp" BOOLEAN DEFAULT (0),
    "texture_factor_red" FLOAT DEFAULT (0_0),
    "texture_factor_green" FLOAT DEFAULT (0_0),
    "texture_factor_blue" FLOAT DEFAULT (0_0),
    "texture_intensity" FLOAT DEFAULT (0_0),
    "texture_contrast" FLOAT DEFAULT (0_0),
    "texture_saturation" FLOAT DEFAULT (0_0),
    "use_map_diffuse" BOOLEAN DEFAULT (0),
    "use_map_color_diffuse" BOOLEAN DEFAULT (0),
    "use_map_alpha" BOOLEAN DEFAULT (0),
    "use_map_translucency" BOOLEAN DEFAULT (0),
    "use_map_ambient" BOOLEAN DEFAULT (0),
    "use_map_emit" BOOLEAN DEFAULT (0),
    "use_map_mirror" BOOLEAN DEFAULT (0),
    "use_map_raymir" BOOLEAN DEFAULT (0),
    "use_map_specular" BOOLEAN DEFAULT (0),
    "use_map_color_spec" BOOLEAN DEFAULT (0),
    "use_map_hardness" BOOLEAN DEFAULT (0),
    "use_map_normal" BOOLEAN DEFAULT (0),
    "use_map_warp" BOOLEAN DEFAULT (0),
    "use_map_displacement" BOOLEAN DEFAULT (0),
    "diffuse_factor" FLOAT DEFAULT (0_0),
    "diffuse_color_factor" FLOAT DEFAULT (0_0),
    "alpha_factor" FLOAT DEFAULT (0_0),
    "translucency_factor" FLOAT DEFAULT (0_0),
    "specular_factor" FLOAT DEFAULT (0_0),
    "specular_color_factor" FLOAT DEFAULT (0_0),
    "hardness_factor" FLOAT DEFAULT (0_0),
    "ambient_factor" FLOAT DEFAULT (0_0),
    "emit_factor" FLOAT DEFAULT (0_0),
    "mirror_factor" FLOAT DEFAULT (0_0),
    "raymir_factor" FLOAT DEFAULT (0_0),
    "normal_factor" FLOAT DEFAULT (0_0),
    "warp_factor" FLOAT DEFAULT (0_0),
    "displacement_factor" FLOAT DEFAULT (0_0),
    "blend_type" TEXT DEFAULT ('MIX'),
    "use_rgb_to_intensity" BOOLEAN DEFAULT (0),
    "color" TEXT DEFAULT ('(0_8, 0_8, 0_8)'),
    "invert" BOOLEAN DEFAULT (0),
    "use_stencil" BOOLEAN DEFAULT (0),
    "default_value" FLOAT DEFAULT (0_0),
    "bump_method" TEXT DEFAULT ('BUMP_ORIGINAL'),
    "bump_objectspace" TEXT DEFAULT ('BUMP_VIEWSPACE'),
    "image_uv_blob" BLOB DEFAULT ('None'),
    "influence_color" TEXT DEFAULT ('(0_8, 0_8, 0_8)')
)
